#!/usr/bin/env node
// One-time icon vendoring: downloads every icon in RealIcon's ICON_NAMES from
// the Icons8 CDN (black; white kept as belt-and-braces) into assets/icons/
// and generates src/components/icons.gen.ts with a require() map.
//
// Why: icons were fetched from the network at runtime — with the tint baked
// into the URL, the ACTIVE tab icon was a different URL than the inactive one,
// so the first tap of every tab did a live network fetch + decode (visible
// flash/jank). Local assets + expo-image tintColor kill that entirely.
//
// Run: node scripts/fetch-icons.js   (re-run only when ICON_NAMES changes)

const fs = require('fs');
const path = require('path');
const https = require('https');

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'assets', 'icons');
const GEN_FILE = path.join(ROOT, 'src', 'components', 'icons.gen.ts');

// Parse ICON_NAMES from RealIcon.tsx so this script never drifts from it.
const realIconSrc = fs.readFileSync(path.join(ROOT, 'src', 'components', 'RealIcon.tsx'), 'utf8');
const block = realIconSrc.match(/export const ICON_NAMES = \{([\s\S]*?)\} as const;/);
if (!block) { console.error('ICON_NAMES block not found'); process.exit(1); }
const slugs = new Set();
for (const m of block[1].matchAll(/:\s*'([a-z0-9-]+)'/g)) slugs.add(m[1]);
console.log(`Found ${slugs.size} distinct icon slugs`);

function download(url, dest) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode !== 200) { res.resume(); return reject(new Error(`${res.statusCode} ${url}`)); }
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => { fs.writeFileSync(dest, Buffer.concat(chunks)); resolve(); });
    }).on('error', reject);
  });
}

(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const ok = [];
  for (const slug of slugs) {
    const black = path.join(OUT_DIR, `${slug}.png`);
    const white = path.join(OUT_DIR, `${slug}-w.png`);
    try {
      if (!fs.existsSync(black)) await download(`https://img.icons8.com/ios-filled/188/000000/${slug}.png`, black);
      if (!fs.existsSync(white)) await download(`https://img.icons8.com/ios-filled/188/FFFFFF/${slug}.png`, white);
      ok.push(slug);
      process.stdout.write('.');
    } catch (e) {
      console.warn(`\nSKIP ${slug}: ${e.message}`);
    }
  }
  console.log(`\nDownloaded ${ok.length}/${slugs.size}`);

  const lines = ok.sort().map((s) => `  '${s}': require('../../assets/icons/${s}.png'),`);
  const wLines = ok.sort().map((s) => `  '${s}': require('../../assets/icons/${s}-w.png'),`);
  fs.writeFileSync(GEN_FILE, `// AUTO-GENERATED by scripts/fetch-icons.js — do not edit by hand.
// Local copies of the Icons8 ios-filled icons used by RealIcon. Black set is
// tinted at render time via expo-image tintColor; the white set is a stored
// fallback in case tinting ever misbehaves on a platform.
export const LOCAL_ICONS: Record<string, number> = {
${lines.join('\n')}
};
export const LOCAL_ICONS_WHITE: Record<string, number> = {
${wLines.join('\n')}
};
`);
  console.log(`Wrote ${GEN_FILE}`);
})();
